# Protocol constants for both server and client
UUID_SIZE = 16
PUBLIC_KEY_SIZE = 160
CLIENT_NAME_SIZE = 255
PACKED_CLIENT_ENTRY_SIZE = UUID_SIZE + CLIENT_NAME_SIZE
REGISTER_REPLY_SIZE = UUID_SIZE + 7  # header + uuid
RESPONSE_HEADER_SIZE = 7


class Code:
    REGISTER = 600
    CLIENT_LIST = 601
    PUBLIC_KEY_REQUEST = 602
    REGISTER_REPLY = 2100
    CLIENT_LIST_REPLY = 2101
    PUBLIC_KEY_REPLY = 2102
    ERROR = 9000
